[package]
name = "postmodern-cli"
description = "CLI for postmodern job queue management."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
readme = "README.md"
keywords = ["postgres", "job-queue", "cli", "database"]
categories = ["command-line-utilities", "database"]

[[bin]]
name = "pm"
path = "src/main.rs"
doc = false

[dependencies]
anyhow = { workspace = true }
clap = { version = "4", features = ["derive"] }
futures = { workspace = true }
rmpv = { version = "1", features = ["with-serde"] }
serde = { workspace = true }
serde-saphyr = "0.0"
tabled = "0.17"
terminal_size = "0.4"
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
uuid = { workspace = true }
uuid-suffix = "0.1.2"
postmodern = { version = "0.5.1", path = "../postmodern" }

[dev-dependencies]
insta = "=1.43.2"
