[workspace]
resolver = "2"
members = ["xpq", "xpq-cli"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mbr/xpq"
authors = ["Marc Brinkmann <git@marcbrinkmann.de>"]

[workspace.dependencies]
anyhow = "1"
futures = "0.3"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["sync", "time"] }
uuid = { version = "1", features = ["v7"] }
