[package]
name = "xpq-cli"
description = "CLI for xpq job queue management."
version.workspace = true
edition.workspace = true

[[bin]]
name = "xpq"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { version = "4", features = ["derive"] }
futures = { workspace = true }
rmpv = { version = "1", features = ["with-serde"] }
serde = { workspace = true }
serde-saphyr = "0.0"
tabled = "0.17"
terminal_size = "0.4"
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
uuid = { workspace = true }
xpq = { path = "../xpq" }

[dev-dependencies]
insta = "=1.43.2"
