[package]
name = "xpq"
description = "Postgres-backed job queue with transaction-based locking."
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
async-stream = { workspace = true }
backon = { workspace = true }
chrono = { workspace = true }
dirs = { workspace = true }
futures = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
pgdb = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
